// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqcNouU9fhlhzXng0JGMYDLrwP9YSHME',
    appId: '1:437709008389:web:df546346a99502906f366c',
    messagingSenderId: '437709008389',
    projectId: 'lumina-portfolio-12345',
    authDomain: 'lumina-portfolio-12345.firebaseapp.com',
    storageBucket: 'lumina-portfolio-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZszk4VUmtfhakblGHv4zZlo4hG5j6jY0',
    appId: '1:437709008389:android:07007c24b6f9cdbf6f366c',
    messagingSenderId: '437709008389',
    projectId: 'lumina-portfolio-12345',
    storageBucket: 'lumina-portfolio-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgS8Nuoc7em1apCvi8jIvJPU0VLI6e_o',
    appId: '1:437709008389:ios:e024c0815d16f9af6f366c',
    messagingSenderId: '437709008389',
    projectId: 'lumina-portfolio-12345',
    storageBucket: 'lumina-portfolio-12345.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzgS8Nuoc7em1apCvi8jIvJPU0VLI6e_o',
    appId: '1:437709008389:ios:e024c0815d16f9af6f366c',
    messagingSenderId: '437709008389',
    projectId: 'lumina-portfolio-12345',
    storageBucket: 'lumina-portfolio-12345.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpqcNouU9fhlhzXng0JGMYDLrwP9YSHME',
    appId: '1:437709008389:web:d77fd8d1b83b14e66f366c',
    messagingSenderId: '437709008389',
    projectId: 'lumina-portfolio-12345',
    authDomain: 'lumina-portfolio-12345.firebaseapp.com',
    storageBucket: 'lumina-portfolio-12345.firebasestorage.app',
  );
}
